### ISSUE TITLE
Customizing number of threads to use

### ISSUE THREAD

**Issue by leonrjg** [iTaybb/pySmartDL#12]
It seems PySmartDL doesn't support custom threads number, as it always uses 5.
I think this would be an useful option.

**Comment by AlexSilverSword** [comment]
Hi @iTaybb 

Your downloader package is the best ever python downloader ever, it is like the python version of IDM but it  is missing the option to change amount of threads to be use directly from the SmartDL class, parameter inputs and basically only need to be changed to:

`SmartDL(self,` urls, dest=None, progress_bar=True, fix_urls=True, logger=None, connect_default_logger=False, **threads_count=12**):
      `self.threads_count` = `threads_count`

I am using python 3 and are install you package through pip, thus this change would be greatly appreciated if it effects the package available on the PYPI website.

Thank you for such an amazing downloader keep up the great work

**Comment by iTaybb** [comment]
I'll add it later today.

**Comment by AlexSilverSword** [comment]
Thank you @iTaybb. I can't say this enough you downloader are amazing and brilliant downloader, you account for most everything need for a Smart downloader package.

**Comment by iTaybb** [comment]
Added in pySmartDL 1.2.5.
