### ISSUE TITLE
Completes download, restarts, runtime error

### ISSUE THREAD

**Issue by OneVoltTen** [iTaybb/pySmartDL#18]
`[*] 236.0 MB / 236.0 MB @ 0 bytes/s [##################] [100%, 0s left]`
 `[*] 236.0 MB / 236.0 MB @ 267 kB/s [##################] [100%, 0s left]`
`<class 'RuntimeError'> cannot join thread before it is started`

URL [https://streaming.lemonstream.me/*****] from https://gostream.is/film/rick-and-morty-season-1-9011/watching.html?ep=127301.

**Comment by iTaybb** [comment]
Fixed.
