### ISSUE TITLE
ssl certificate

### ISSUE THREAD

**Issue by ElissonRodrigues** [iTaybb/pySmartDL#38]
I have the download link that has the ssl certificate expired. Can you add an option to bypass ssl certificate verification?

And I would also like PySmartDL to have an option to be able to customize the name of the file.

**Comment by Blatzar** [comment]
Having the same ssl issue. Code below for example:
```
from pySmartDL import SmartDL

url = 'https://s5.mp4upload.com:282/d/qcxwdwykz3b4quuoaowbs2ysjdmoptqcyxrvickuj63o3i42pjjtn52f/yavideo.mp4'

obj = SmartDL(url, progress_bar=True)
obj.start()
```
I'm pretty sure you can customize name of the file by changing destination :man_shrugging:
