### ISSUE TITLE
Is there pause and resume support planned?

### ISSUE THREAD

**Issue by wxguy** [iTaybb/pySmartDL#4]
As stated in the heading, is there any pause and resume support down the line in future versions?
Also is there any option to set the 'pySmartDL' to try 'n' time for downloading a file?

**Comment by iTaybb** [comment]
Pause & Resume is already supported. Are you having any issues with it?
Regarding the retries - no such feature is implemented inside pySmartDL, but it's really easy to implement it yourself. Just put it in a loop.

**Comment by wxguy** [comment]
"Pause & Resume is already supported."
I didn't know about this. Is there any documentation for this? If not then atleast a sentence in the official documentation would be good.

Closing the issue as the feature requested is already existing in tthe package.
