### ISSUE TITLE
Error while downloading  🤒

### ISSUE THREAD

**Issue by Clinton-Abraham** [iTaybb/pySmartDL#56]
![Screenshot_2022-06-07-15-06-17-072_com chsappz hmanager](https://user-images.githubusercontent.com/70835540/172358578-f8897a5e-37f3-43ad-9ac8-295f740e3cab.jpg)

**Comment by 4LINUXUSER4** [comment]
I have the same issue, I've been beating up my code when it was just Smartdl killing me, did u solve it yet?

**Comment by Clinton-Abraham** [comment]
> I have the same issue, I've been beating up my code when it was just Smartdl killing me, did u solve it yet?

No :(

**Comment by Clinton-Abraham** [comment]
Fixed 🙂
