### ISSUE TITLE
Downloading in parts

### ISSUE THREAD

**Issue by neox387** [iTaybb/pySmartDL#7]
Would be nice if this could download in 1 file, so combining isn't needed as this is very slow if for example you download to a network location.

I think queue can do this ? like this one:
https://github.com/DiSiqueira/DSDownload

**Comment by iTaybb** [comment]
You cannot download to a single file if you're using multiple threads for downloading.
If you'll use only one thread (by passing threads=1) it'll be created in a single file. But you won't get better performance gained by multiple threads.

**Comment by neox387** [comment]
Should still be some way to do this, like i linkt above multiple download threads putting the parts to queue that uses 1 thread to write ?

I'm downloading to my nas & after all parts are done downloading it takes ages because it has to read the parts again & write it again to create the final file, with Jdownload it's instantly done.

anyway for a 1 thread download i just rename the file no need for another read/write ..

````
if len(parts) == 1:
  os.rename(parts[0],dest)
````

**Comment by iTaybb** [comment]
Got what you're saying. I'll fix it.

**Comment by iTaybb** [comment]
Improved in pySmartDL 1.2.5.
